\LoadClass[a4paper,conference,10pt]{IEEEtran}
\IEEEoverridecommandlockouts
\setlength{\parskip}{3pt}

\setlength{\marginparwidth}{0pt}
\setlength{\marginparsep}{0pt}
    
\setlength{\columnwidth}{0.25in}

\usepackage{geometry}
\geometry{nomarginpar, a4paper, left=0.72in, right=0.72in, top=1in, bottom=1in, columnsep=0.25in}


\renewcommand\footnoterule{\hspace{-1em}\rule{\linewidth}{0.8pt}\vspace{0.2em}}
