\LoadClass[a4paper,conference,10pt]{IEEEtran}
\IEEEoverridecommandlockouts
\setlength{\parskip}{3pt}

\def\BibTeX{{\rm B\kern-.05em{\sc i\kern-.025em b}\kern-.08em
    T\kern-.1667em\lower.7ex\hbox{E}\kern-.125emX}}
    
\usepackage{geometry}
\geometry{a4paper, left=20mm, right=20mm, top=25mm, bottom=25mm}

\usepackage[justification=centering]{caption}

\renewcommand\footnoterule{\hspace{-1em}\rule{\linewidth}{0.8pt}\vspace{0.2em}}

%\NewCommandCopy{\oldthanks}{\thanks}
%\renewcommand{\thanks}[1]{\oldthanks{#1}}